version: '3.7'

services:
  transmission_bd:
    image: cassandra:3.11.9
    ports:
    - 9042:9042
    restart: always
    environment:
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M

  transmission_ms:
    image: ms_trx
    ports:
    - 8000:8000
    restart: always
    environment:
      CASS_URL: "transmission_bd:9042"
      CASS_DB: transmission
      CASS_PASS: passwordSeguro
      CASS_USR: userSeguro
      PORT: 8000

  transmission_nw:
    image: praqma/network-multitool:extra

  transmission_bd_gui:
    image: metavige/cassandra-web
    ports:
    - 8500:3000
    environment:
      CASSANDRA_HOST: "192.168.0.2"
      CASSANDRA_USER: userSeguro
      CASSANDRA_PASSWORD: passwordSeguro

networks: 
  default: 
      name: meet-network